An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0572.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbf10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6284/spec-6284-56310-0670.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ff40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0614.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e050>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0067.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8bb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0054.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca2f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0721.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb850>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/3587/spec-3587-55182-0298.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ee90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0791.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ca00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0448.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca170>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0942.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9c00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0078.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb100>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0630.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9a20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4221/spec-4221-55443-0842.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ca90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0274.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cf40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0028.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9db0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0957.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb0a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0577.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0643.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c8e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0296.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4369/spec-4369-55827-0422.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca3b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0750.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8d30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0142.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb520>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0754.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb220>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0561.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fe80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/3588/spec-3588-55184-0566.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0065.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cba90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0245.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca620>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0526.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca350>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0436.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e470>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0092.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f790>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0684.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb910>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0869.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cba00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0640.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c89a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0724.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f6d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0068.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e470>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0766.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d5a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0934.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca9e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0866.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbfa0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0736.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb820>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0634.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e050>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0760.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e170>: Failed to establish a new connection: [Errno 61] Connection refused')))
10936it [2:54:24, 178.34it/s]An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0686.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca050>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0285.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca560>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0923.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cabc0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4303/spec-4303-55508-0300.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c6d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0686.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d030>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0749.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb1f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0536.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb010>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0681.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb280>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0974.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca230>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0438.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d1e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0157.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723eda0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0094.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb700>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0607.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb670>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0554.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca170>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0019.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f640>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4418/spec-4418-55862-0024.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f280>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0129.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb040>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0440.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cab60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0739.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca200>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0961.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbe50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0625.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c430>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0251.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e050>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0883.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbbb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6192/spec-6192-56269-0968.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbac0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0277.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cafe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0968.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0725.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c0a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0138.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9a20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0748.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca0b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4418/spec-4418-55862-0964.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7153/spec-7153-56904-0607.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c8e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0255.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0120.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d3f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0590.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9ed0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0094.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbeb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/1086/spec-1086-52525-0151.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca9e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0979.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e170>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0056.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0730.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb460>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0540.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbd00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6284/spec-6284-56310-0706.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171caf80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0042.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c1f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0947.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d450>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0627.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca350>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0962.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbb80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0719.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9870>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0690/spec-0690-52261-0385.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8be0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0594.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d8d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0495.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dd50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0506.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cad40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0272.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbc10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0072.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb1f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0276.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c190>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0156.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d210>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0680.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c89a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0011.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8dc0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0523.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbd30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0732.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171caf20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0267.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d3c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0678.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e170>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0850.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb2b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0268.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cae90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0269.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb820>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0250.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fd30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0278.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cdf0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0360.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb7c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0868.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9ab0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0928.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8d00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0243.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f4f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0733.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fd30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0582.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ded0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/3586/spec-3586-55181-0958.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbf10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0296.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca470>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0860.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9ed0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0654/spec-0654-52146-0029.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0432.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d5a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0370.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca740>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0030.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb250>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0755.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb400>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0692.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e920>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0574.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0755.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cafe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0782.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca920>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6187/spec-6187-56244-0970.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb340>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0362.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb280>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0266.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fd90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0327.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d360>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0273.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb910>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0052.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8a60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4540/spec-4540-55863-0950.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca350>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0642.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723caf0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0740.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f370>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0951.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0310.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb4f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6188/spec-6188-56208-0686.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbca0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0262.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0240.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c1c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7040/spec-7040-56574-0462.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0262.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca4a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0762.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb430>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6193/spec-6193-56237-0690.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca9e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0048.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d150>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0484.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f9a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0969.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbc40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0767.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171caa40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0061.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbdf0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0774.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c190>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0691.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d150>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0666.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d6c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0978.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb1f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0300.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8a60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0086.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca350>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0781.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d5a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0715.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d3f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0988.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb700>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0262.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca0b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4221/spec-4221-55443-0084.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca410>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0320.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e4a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7040/spec-7040-56574-0428.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e050>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4304/spec-4304-55506-0431.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca620>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/3588/spec-3588-55184-0470.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca680>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0910.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca6e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0062.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8a00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0690/spec-0690-52261-0409.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ece0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6193/spec-6193-56237-0662.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f640>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0722.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb220>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0096.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbe20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0236.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cafe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0764.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c610>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/5656/spec-5656-55940-0288.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fc10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0683.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cae00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0540.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca470>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0238.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbbe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0135.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb040>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0268.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c2b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0466.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d5a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0421.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9810>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0930.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbd30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0270.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cada0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0418/spec-0418-51817-0191.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cd90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0607.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dd50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0334.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9c90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0438.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb280>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0004.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0230.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723caf0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0900.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cd90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0030.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d9c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0774.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9db0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4304/spec-4304-55506-0560.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb430>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0277.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb1f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0380.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d3f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4418/spec-4418-55862-0992.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ded0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0148.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9ed0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0319.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cba90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0784.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbf10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0264.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723da50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0690/spec-0690-52261-0431.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e170>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0018.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbb80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0439.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171caf20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0602.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb2b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6193/spec-6193-56237-0354.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cad40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0034.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cc10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0394.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0332.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cad70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0670.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c89a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0788.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca620>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6284/spec-6284-56310-0294.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ec80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/9346/spec-9346-57751-0006.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723de10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0560.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb9d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0655/spec-0655-52162-0289.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0418/spec-0418-51817-0186.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca560>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6284/spec-6284-56310-0316.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca4a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0796.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c3d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0104.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d3f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0398.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb850>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0431.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cba00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0045.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9db0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0895.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723eda0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0921.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d360>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0638.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9c00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7040/spec-7040-56574-0564.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8a00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/3586/spec-3586-55181-0038.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca710>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0062.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c610>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0947.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723eda0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8750/spec-8750-58401-0520.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cd00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0772.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb3a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0070.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbd30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/1086/spec-1086-52525-0508.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb370>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0678.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d5a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0702.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d6c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
11126it [2:54:24, 308.62it/s]An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0044.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbb80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0062.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb400>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0202.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb160>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0060.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f7f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0312.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6529/spec-6529-56535-0494.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0330.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbbb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0620.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8be0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0412.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9870>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0085.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dc90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0778.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e3e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0418.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171caec0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0206.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb9d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0273.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca920>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0441.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f190>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0672.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fe50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-0981.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb6a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6196/spec-6196-56189-0866.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbfd0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0610.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb190>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0418/spec-0418-51817-0449.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cac80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0306.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cf40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0673.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d5a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0382.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbf10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0783.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cba90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0424.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb910>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0774.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d8d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0777.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f640>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0699.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cab60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0917.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0060.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca470>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0720.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ec80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0268.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d8d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0228.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c040>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0817.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0410.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb4f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6196/spec-6196-56189-0893.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb3a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0920.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d6c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8750/spec-8750-58401-0498.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d030>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0946.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0268.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbeb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0250.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb250>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0789.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d9f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0765.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f400>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0406.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb8e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6873/spec-6873-56541-0556.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca7d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0925.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca740>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0238.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb2b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0066.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e6e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0780.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fcd0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0950.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8dc0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0470.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb1f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0227.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0404.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f370>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6284/spec-6284-56310-0758.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c700>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0774.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca710>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0064.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca440>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0644.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca4d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0602.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbca0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0977.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f8b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0762.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e140>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4304/spec-4304-55506-0404.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca050>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0084.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca200>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0526.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb370>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0781.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ef20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8750/spec-8750-58401-0505.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0928.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbf40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0430.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbfa0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6526/spec-6526-56543-0069.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb3d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8748/spec-8748-58396-0054.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f190>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0764.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ef20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0940.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d3c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0370.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbc10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0704.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb220>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0778.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0247.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d030>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0420.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cd00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/9442/spec-9442-58076-0892.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbbe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0609.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca620>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7152/spec-7152-56660-0943.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c89a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0310.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cbb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0794.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d600>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0888.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb910>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6196/spec-6196-56189-0874.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cabc0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0800.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbe80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0230.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8be0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0416.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e080>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0718.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ce50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6196/spec-6196-56189-0102.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9c00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0580.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca8c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0944.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb8e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0948.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723de40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0891.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c100>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0328.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca470>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0282.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca680>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0324.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb670>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0077.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9a80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8750/spec-8750-58401-0514.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ef80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0228.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d030>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4303/spec-4303-55508-0236.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb550>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0222.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca2f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0706.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb3a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0813.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0714.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e3e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0361.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9c60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0764.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cada0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0798.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca110>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0297.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f370>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0114.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0075.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f3d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/5656/spec-5656-55940-0254.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb460>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0728.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb850>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4419/spec-4419-55867-0535.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbc10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6283/spec-6283-56239-0092.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cd00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0905.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fe50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6198/spec-6198-56211-0444.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cba30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0588.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9ab0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0974.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb0a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0562.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dcc0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0066.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cfd0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7040/spec-7040-56574-0452.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0712.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0465.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca560>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0236.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca470>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0266.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0390.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e320>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0789.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbd30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0232.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4540/spec-4540-55863-0056.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8a00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7905/spec-7905-57666-0520.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0480.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cb20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0030.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb010>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0370.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb490>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0290.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb9a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8750/spec-8750-58401-0502.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca740>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0655/spec-0655-52162-0244.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fa00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6193/spec-6193-56237-0284.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cd00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6201/spec-6201-56186-0760.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8bb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0578.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8a60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0280.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbf40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0352.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fd90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0234.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fcd0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0732.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca4a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0034.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8970>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0396.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca440>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0050.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723de40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0119.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fd90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0043.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e170>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0660.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171caec0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0233.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb400>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0101.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb4f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0745.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fe50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0464.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d3c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0574.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb0d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0894.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbb80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/9409/spec-9409-58051-0240.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb190>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0806.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723da20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0798.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c040>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0210.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb7c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0229.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb9d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7867/spec-7867-57003-1000.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9900>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0804.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca410>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4419/spec-4419-55867-0466.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c760>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0901.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723eef0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0830.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca710>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0027.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8b80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0009.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0969.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723df30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0648.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f010>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0738.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb670>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0464.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb910>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0088.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbfd0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0216.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbbe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0817.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723db10>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0028.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fe50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4303/spec-4303-55508-0812.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb430>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7716/spec-7716-58097-0489.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca7d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0220.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca140>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0714.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d450>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0802.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c430>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0472.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbe50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0824.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbee0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0720.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9c60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7905/spec-7905-57666-0447.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dde0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7716/spec-7716-58097-0512.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d450>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0376.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fbb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/5656/spec-5656-55940-0240.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb460>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0965.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca050>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4542/spec-4542-55833-0468.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171caec0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0474.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dbd0>: Failed to establish a new connection: [Errno 61] Connection refused')))
11315it [2:54:24, 462.90it/s]An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0223.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d210>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0227.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbe80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0215.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c89a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0804.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca620>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0662.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c190>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0110.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ece0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0270.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca2f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0746.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca4d0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0585.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0997.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca560>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0594.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e470>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7040/spec-7040-56574-0592.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723cbb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0822.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca350>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0043.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cac50>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0592.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb7c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0299.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ceb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7904/spec-7904-57358-0828.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0188.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbf40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0195.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca920>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0575.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbeb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0814.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cab60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0046.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d540>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7716/spec-7716-58097-0500.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dbd0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0726.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9810>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0995.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb040>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0042.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca410>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0236.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dd80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0955.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f790>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6283/spec-6283-56239-0976.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca0b0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0986.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb010>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0380.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca440>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7855/spec-7855-57011-0990.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723de40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7715/spec-7715-57364-0264.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723dd80>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0706.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f3a0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0834.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb880>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4303/spec-4303-55508-0781.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9db0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7152/spec-7152-56660-0983.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb460>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0600.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d210>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0584.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0184.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbbe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7660/spec-7660-57357-0037.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cafe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0984.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb820>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0587.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e110>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0784.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fbe0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0570.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca140>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6201/spec-6201-56186-0766.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8c40>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7672/spec-7672-57339-0660.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbc70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0734.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9900>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7716/spec-7716-58097-0506.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e3e0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0559.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723eef0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4369/spec-4369-55827-0620.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb4f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4418/spec-4418-55862-0010.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbbb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0554.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca2f0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7040/spec-7040-56574-0393.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ee90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0375.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ca90>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0564.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9c60>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11047/spec-11047-58424-0516.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cba00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0628.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb520>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11314/spec-11314-58436-0035.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9a20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0582.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723e650>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7716/spec-7716-58097-0514.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d210>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11046/spec-11046-58398-0736.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbfa0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6198/spec-6198-56211-0562.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbe20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/4304/spec-4304-55506-0420.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171caec0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0750.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ef20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0807.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f520>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7671/spec-7671-57360-0626.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb610>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/9350/spec-9350-58081-0751.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cbca0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7716/spec-7716-58097-0498.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cad70>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7869/spec-7869-57012-0421.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ceb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7856/spec-7856-57260-0550.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723ef20>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0186.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723fdc0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7588/spec-7588-56903-0207.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb280>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7714/spec-7714-57363-0936.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c8bb0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0161.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb880>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7713/spec-7713-58096-0206.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c940>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6196/spec-6196-56189-0902.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723d450>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8750/spec-8750-58401-0536.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9ed0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0744.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cae00>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7616/spec-7616-56902-0431.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cb160>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7868/spec-7868-57006-0169.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723f280>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0914.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723c1c0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/11047/spec-11047-58424-0518.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca410>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0302.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171ca110>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/7615/spec-7615-56977-0116.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171cada0>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/8749/spec-8749-57684-0754.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1171c9f30>: Failed to establish a new connection: [Errno 61] Connection refused')))
An error occurred: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/6197/spec-6197-56191-0738.fits (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11723caf0>: Failed to establish a new connection: [Errno 61] Connection refused')))
11413it [2:54:41, 24.41it/s]HTTP error occurred: 404 Client Error: Not Found for url: https://data.sdss.org/sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0690/spec-0690-52261-0462.fits
An error occurred: ('Connection broken: IncompleteRead(425724 bytes read, 1498116 more expected)', IncompleteRead(425724 bytes read, 1498116 more expected))
11470it [3:11:27,  2.57s/it]HTTP error occurred: 404 Client Error: Not Found for url: https://data.sdss.org/sas/dr17/eboss/spectro/redux/v5_13_2/spectra/full/0690/spec-0690-52261-0177.fits
11524it [3:12:27,  1.31s/it]An error occurred: ('Connection broken: IncompleteRead(737020 bytes read, 1014020 more expected)', IncompleteRead(737020 bytes read, 1014020 more expected))
11566it [3:29:07,  1.07it/s]An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))